#!/bin/bash

. ../functions
. ../audio_functions

RECORD_TIME=10

ask_continue $(txtmenu_from_file Audio_pg1.txt)

res=$(get_audio_output_device); ask_continue; log "${res}"

progress_view_dummy ${RECORD_TIME} --auto-close &
playback_output=$(timeout ${RECORD_TIME} \
gst-launch alsasrc ! audioconvert ! audioresample ! wavenc ! \
filesink location=recording.wav)
log "${playback_output}"

# play it back
play_output=$(gst-launch playbin2 uri=file://"$(pwd)"/recording.wav 2>&1) &
progress_view_dummy ${RECORD_TIME} --auto-close
log "${play_output}"

result=$(logged_feedback_menu "recording" audio_feedback.menu)
stat=$(current_status "" $(get_feedback_status "${result}"))

echo ${stat}
