#!/bin/bash

. ../functions
. ../audio_functions

RECORD_TIME=10

ask_continue $(txtmenu_from_file Audio_pg1.txt)

res=$(get_audio_output_device); ask_continue; log "${res}"

timeout ${RECORD_TIME} \
sox -t alsa default ./recording.wav 2>&1 | \
tr \\r \\n | \
progress_view ${RECORD_TIME} '' '' --enable-log --log-expanded

# play it back
log "$(aplay ./recording.wav 2>&1)" &
progress_view_dummy ${RECORD_TIME} --auto-close

result=$(logged_feedback_menu "recording" audio_feedback.menu)
stat=$(current_status "" $(get_feedback_status "${result}"))

echo ${stat}
