#!/bin/bash

. ../functions
. ../network_functions

network_feedback_menu()
{
	stage=${1}

	log "After running stage ${stage}"
	log_default_feedback network_feedback.menu
}

network_good()
{
	log "Network test successful"
	echo "Success"
}

network_problem()
{
	log_default_describe_problem "Timeout" "Other"

	echo "Failure"
}

ask_continue $(txtmenu_from_file Network_pg1.txt)

url=$(get_url "wikipedia.org")

host_output=$(host "${url}"); ret_code=$?

log "${host_output}"

if [ "0" = "${ret_code}" ]
then
	echo "Success"
else
	echo "Failure"
fi
