#!/bin/bash

. ../functions
. ../network_functions

ask_continue $(txtmenu_from_file Network_pg1.txt)

url=$(get_url "wikipedia.org")

host_output=$(host "${url}"); ret_code=$?

log "${host_output}"

if [ "0" = "${ret_code}" ]
then
	echo "Success"
else
	echo "Failure"
fi
