#!/bin/bash

# buttons
cancelBtn="1"
closeBtn="252"
okBtn="0"

MAIN_MENU="--list --column=Test --column=Status --column=@fore@"
FEEDBACK_MENU="--list --column=:RD --column=Status --column=Action:HD"

close_menu()
{
	btn=${1}

	if [ ${btn} -eq "0" ]
	then
		return 1
	else
		return 0
	fi
}

mk_menu_body()
{
	local file=${1}
	local process=${2}

	if [ -z "${process}" ]
	then
		process="echo"
	fi

	local accum_body=""
	local tmp=""

	while read line
	do
		tmp=$(${process} ${line})
		accum_body="${accum_body} ${tmp}"
	done < ${file}

	echo ${accum_body}
}

config_main_menu_item()
{
	local hwtest=${1}
	local status=${2}
	local color=""

	case ${status} in
		Incomplete)
			color="black"
			;;
		Failure)
			color="red"
			;;
		Success)
			color="green"
			;;
		*)
			color="orange"
			;;
	esac

	echo ${hwtest} ${status} ${color}
}

update_test_status()
{
	local testName=${1}
	local status=${2}
	local fileName=${3}

	if [ -z "${status}" ]
	then
		exit 0
	fi

	echo ${testName}

	while read line
	do
		if [[ $line == ${testName}* ]]
		then
			echo "${testName} ${status}" >> tmp_menu_file
		else
			echo "${line}" >> tmp_menu_file
		fi
	done < ${fileName}

	mv tmp_menu_file ${fileName}
}

parse_item()
{
	echo ${1} | cut -d"|" -f1
}
