#!/bin/bash

. ./functions

if [ ! -e main_menu.dat ]
then
	./init_main_menu < hardware_list.dat > main_menu.dat
fi

while :
do
	menu_item=$(yad ${MAIN_MENU} $(mk_menu_body main_menu.dat config_main_menu_item))
	btn=$?

	echo "${menu_item}"
	echo "${btn}"

	if close_menu ${btn}
	then
		break
	fi

	if [ ! -z "${menu_item}" ]; then
		choice=./$(parse_item ${menu_item})
		cd ${choice}; status=$(./launch); cd ..
		echo "Result is: ${status}"

		update_test_status ${choice} ${status} main_menu.dat
	fi
done
