#!/bin/bash

. ./functions

TEST_NAME=2
RESULT_STATUS=3

main_menu()
{
    yad_default_menu --height=350 --list \
--column="":IMG --column=Test --column=Status --column=@fore@ \
--rest=main_menu.dat
}

launch_test()
{

	if [ ! -z "${old_stat}" ] && [ ! "${old_stat}" = "Incomplete" ]
	then
		ask_continue $(yad_default_menu \
--text="This test has already been run, with status: ${old_stat}\n\
Please review the log file below before proceeding" \
--text-info --filename="${choice}"/log) >> /dev/null
	fi

	# now entering
	cd "${choice}"
		init_test_log
		status=$(./launch)
	cd ..
	# now exiting

	update_test_status "${choice}" ${status} main_menu.dat
}

if [ ! -e main_menu.dat ]
then
	./init_status_list < hardware_list.dat > main_menu.dat
fi

while :
do
	menu_item=$(main_menu)
	ask_continue > /dev/null # hacky but it works

	if [ ! -z "${menu_item}" ]; then
		choice=$(parse_item ${TEST_NAME} "${menu_item}")
		old_stat=$(parse_item ${RESULT_STATUS} "${menu_item}")

		$(launch_test) > /dev/null
	fi
done
