#!/bin/bash

. ../functions
. ../audio_functions

BEETHOVEN_TIME=10

ask_continue $(txtmenu_from_file Audio_pg1.txt)

res=$(yad_default_menu \
--text="Please select your audio output device" \
--list --column="":RD --column="Device" \
FALSE Headphones \
TRUE "Built-in Speakers")
ask_continue

log "${res}"

progress_view_dummy ${BEETHOVEN_TIME} --auto-close &
gst_launch_output=$(timeout ${BEETHOVEN_TIME} \
gst-launch playbin2 uri=file://"$(pwd)"/clip.mp3 2>&1)

log "${gst_launch_output}"

result=$(logged_feedback_menu "mp3_playback" audio_feedback.menu)
stat=$(current_status "" $(get_feedback_status "${result}") )

echo "${stat}"
