#!/bin/bash

. ../functions

PING_TIME=15

network_feedback_menu()
{
	stage=${1}

	log "After running stage ${stage}"
	log_default_feedback network_feedback.menu
}

network_good()
{
	echo "Success"
}

network_problem()
{
	log_default_describe_problem "Timeout" "Other"

	echo "Failure"
}

ask_continue $(txtmenu_from_file Network_pg1.txt)

url=$(parse_item 1 $(yad --text="Please provide a URL below (default of wikipedia.org)" --form --field="URL")); ask_continue

if [ -z "${url}" ]
then
	url="wikipedia.org"
fi

log "Running ping test on ${url}"
ping -w ${PING_TIME} ${url} 2>&1 | progress_view ${PING_TIME} "" "" --enable-log --log-expanded

result=$(network_feedback_menu "ping")
stat=$(current_status "" $(get_feedback_status "${result}") )

echo "${stat}"
