#!/bin/bash

. ../functions

PINKNOISE_TIME=10
BEETHOVEN_TIME=10

# TODO make sure user actually picks an option!
audio_feedback_menu()
{
	local stage=${1}

	yad ${FEEDBACK_MENU} \
"" "No audio" "audio_none ${stage}" \
"" "Problem with Audio" "audio_problem ${stage}" \
"" "Audio Playback OK" "audio_good ${stage}"
}

audio_good()
{
	# TODO
	echo "Success"
}

audio_problem()
{
	local res=$(yad --text="Please select the most appropriate" --form \
--field=Skipping:CHK FALSE \
--field=Distortion:CHK FALSE \
--field=Other:CHK FALSE \
--field="Leave any comments below":TXT)

	echo "Failure"
}

audio_none()
{
	echo "Failure"
}

ask_continue $(yad --text="$(cat Audio_pg1.txt)")


$(timeout ${PINKNOISE_TIME} speaker-test -l 1 > /dev/null) &
progress_view ${PINKNOISE_TIME}

# TODO reading multi-word list entries from a file is
# harder than expected
# TODO make sure the user picks a choice
result=$(audio_feedback_menu "pink_noise")
stat=$(current_status "" $($(echo ${result} | cut -d "|" -f3)))

ask_continue $(if_failure ${stat})
ask_continue $(yad --text="$(cat Audio_pg2.txt)")

$(timeout ${BEETHOVEN_TIME} mpg321 clip.mp3 > /dev/null) &
progress_view ${BEETHOVEN_TIME}

result=$(audio_feedback_menu "mp3_playback")
stat=$(current_status ${stat} $($(echo ${result} | cut -d "|" -f3)))

echo ${stat}
