#!/bin/bash

. ../functions

audio_feedback_menu()
{
	local stage=${1}

	yad ${FEEDBACK_MENU} \
"" "No audio" "audio_none ${stage}" \
"" "Problem with Audio" "audio_problem ${stage}" \
"" "Audio Playback OK" "audio_good ${stage}"
}

audio_good()
{
	# TODO
	echo "Success"
}

audio_problem()
{
	local res=$(yad --text="Please select the most appropriate" --form \
--field=Skipping:CHK FALSE \
--field=Distortion:CHK FALSE \
--field=Other:CHK FALSE \
--field="Leave any comments below":TXT)

	echo "Failure"
}

audio_none()
{
	echo "Failure"
}

$(yad --text="$(cat Audio_pg1.txt)")
btn=$?

if close_menu ${btn} 
then
	exit 1
fi

#speaker-test -l 1

# TODO reading multi-word list entries from a file is
# harder than expected
# TODO make sure the user picks a choice
result=$(audio_feedback_menu "pink_noise")

if close_menu ${btn}
then
	exit 1
fi

stat=$(current_status "" $($(echo ${result} | cut -d "|" -f3)))

if ! continue_after_failure ${stat}
then
	echo ${stat}
	exit 0
fi

yad --text="$(cat Audio_pg2.txt)"
btn=$?

if close_menu ${btn} 
then
	exit 1
fi

# mpg321 clip.mp3

result=$(audio_feedback_menu "mp3_playback")

if close_menu ${btn}
then
	exit 1
fi

stat=$(current_status ${stat} $($(echo ${result} | cut -d "|" -f3)))

echo ${stat}
