#!/bin/bash

. ../functions

LOREM_COUNT=240000 # IMPORTANT DO NOT CHANGE

md5sum_equal()
{
	local md5sum_output=$(md5sum -c loremipsum.txt.md5sum)
	local res="$(echo ${md5sum_output} | cut -d' ' -f2)"

	log "${md5sum_output}"

	if [ "OK" = "${res}" ]
	then
		echo "Success"
	else
		echo "Failure"
	fi 
}

ask_continue $(txtmenu_from_file SSD_pg1.txt)

zcat loremipsum.txt.gz | pv > loremipsum.txt 2> >(progress_view 1 "" "Unzipping file. Progress bar unavailable" --auto-close)

stat=$(md5sum_equal | tee >(progress_view 1 "" "Checking md5sum. Progress bar unavailable") )

# be nice
rm loremipsum.txt

echo ${stat}
