#!/bin/bash

. ../functions

PANGRAM="Sphinx of black quartz, judge my vow."

while :
do
	ask_continue $(txtmenu_from_file Keyboard_pg1.txt)
	input=$(yad_default_menu --text-info --editable --text="${PANGRAM}")

	res=$(yad_default_menu --form --field="Please confirm the following: you were asked to type":LBL --field="${PANGRAM}":LBL --field="and with the keyboard you typed":LBL --field="${input}":LBL)

	if $(ask_continue) # this function is getting abused...
	then
		log "User asked to type:\n${PANGRAM}\nUser response is:\n${input}"

        if [[ "${input}" = ${PANGRAM} ]]
        then
			log "Keyboard test success"
            yad_stat_menu "Success"
            echo "Success"
        else
			log "Keyboard test failure!"
            yad_stat_menu "Failure"
            echo "Failure"
        fi

		break
	fi
done
