#!/bin/bash

. ../functions
. ../audio_functions

PINKNOISE_TIME=10

ask_continue $(txtmenu_from_file Audio_pg1.txt)

res=$(yad_default_menu \
--text="Please select your audio output device" \
--list --column="":RD --column="Device" \
FALSE Headphones \
TRUE "Built-in Speakers")
ask_continue

log "${res}"

# actual test
progress_view_dummy ${PINKNOISE_TIME} --auto-close &
log $(timeout ${PINKNOISE_TIME} speaker-test -l 1 2>&1)

result=$(logged_feedback_menu "pink_noise" audio_feedback.menu); ask_continue
stat=$(current_status "" $(get_feedback_status "${result}" ) )

echo ${stat}
