#!/bin/bash

. ../functions
. ../audio_functions

BASIC_TEST_TIME=6

run_basic_test()
{
	local ttest="${1}"
	local ttime="${2}"

	progress_view_dummy ${ttime} --auto-close &
	gst_output=$(timeout ${ttime} \
gst-launch audiotestsrc wave=${ttest} ! alsasink 2>&1)
	log "${gst_output}"

	local result=$(logged_feedback_menu "${ttest}" audio_feedback.menu)
	ask_continue

	# UPDATING GLOBAL VARIABLES?!
	local test_stat=$(get_feedback_status "${result}")
	stat=$(current_status "${stat}" ${test_stat})
}

ask_continue $(txtmenu_from_file Audio_pg1.txt)

res=$(get_audio_output_device); ask_continue; log "${res}"

run_basic_test pink-noise ${BASIC_TEST_TIME}

echo ${stat}
